<nav class="navbar navbar-expand-lg menu">
	<div class="container justify-content-center">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Timeline
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
		
	  </div>
	</div>
</nav>

<div class="container mt-5 justify-content-center">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">
								<?= $this->view->info_utilizador['nome']?>
							</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Posts</span><br />
							<span class="perfilPainelItemValor">
								
								<?= $this->view->total_posts['total_posts'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">A seguir</span><br />
							<span class="perfilPainelItemValor">							
								
								<?= $this->view->total_a_seguir['total_a_seguir'] ?> 
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">
								
								<?= $this->view->total_seguidores['total_seguidores'] ?> 
							</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2 justify-content-center">
				<h2>Posts</h2>
			</div>

			<?php foreach($this->view->posts as $id_post => $post) { ?>

			<div class="row post">
				
			
				<div class="col">
					<p><strong><?=$post['nome'] ?></strong> <span style="font-size:12px;" class="text text-muted">- <?=$post['data']?> </span></p>
					<p><?=$post['content']?></p>

					<br />	

				</div>
			
					<?php if($post['id_utilizador'] == $_SESSION['id']) {?>
					<form method="get" action="/remove_post">
						
						<div class="col d-flex justify-content-end">
						<!--	<button href="/remove_post?post_id=<?= ($post['id'])?>" class="btn btn-danger"></button>-->
							<a href="/remove_post?post_id=<?= ($post['id'])?>" class="btn btn-danger"><small><i class="fas fa-trash-alt"></i></small></a>
						</div>
					</form>
				<?php } ?>		
			</div>
		<?php } ?>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>